package assignment2;

/**
 * Sensor Data is the data generated by the sensor
 * 
 * @author bonii
 *
 */
public class SensorReading {
	private float humidity;
	private float temperature;
	public SensorReading (float temp, float hum){
		this.humidity=hum;
		this.temperature = temp;
	}

	public SensorReading() {

	}

	public float getHumidity() {
		return humidity;
	}
	public void setHumidity(float humidity) {
		this.humidity = humidity;
	}
	public float getTemperature() {
		return temperature;
	}
	public void setTemperature(float temperature) {
		this.temperature = temperature;
	}

	@Override
	public String toString() {
		return this.temperature + " " + this.humidity;
	}
}
